version: "2"

services:
  agr_elasticsearch:
    container_name: agr_elasticsearch
    image: ${REG}/agr_elasticsearch_env:develop
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false

  agr_indexer:
    container_name: agr_indexer
    image: agrlocal/agr_indexer_run:develop
    networks:
      - esnet

networks:
  esnet:

