export const LOAD_DATATYPES_BEGIN = 'LOAD_DATATYPES_BEGIN';
export const LOAD_DATATYPES_SUCCESS = 'LOAD_DATATYPES_SUCCESS';
export const LOAD_DATATYPES_FAILURE = 'LOAD_DATATYPES_FAILURE';

export const LOAD_DATATYPE_BEGIN = 'LOAD_DATATYPE_BEGIN';
export const LOAD_DATATYPE_SUCCESS = 'LOAD_DATATYPE_SUCCESS';
export const LOAD_DATATYPE_FAILURE = 'LOAD_DATATYPE_FAILURE';
