
export const LOAD_DATATYPE = 'LOAD_DATATYPE';
export const LOAD_DATATYPES = 'LOAD_DATATYPES';
export const LOAD_DATATYPES_SUCCESS = 'LOAD_DATATYPES_SUCCESS';
export const LOAD_DATATYPE_SUCCESS = 'LOAD_DATATYPE_SUCCESS';
