package org.alliancegenome.neo4j.entity.node;

import java.util.Date;
import java.util.*;

import org.alliancegenome.es.util.DateConverter;
import org.alliancegenome.neo4j.entity.Neo4jEntity;
import org.alliancegenome.neo4j.view.View;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.neo4j.ogm.annotation.NodeEntity;
import org.neo4j.ogm.annotation.typeconversion.Convert;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonView;

import com.fasterxml.jackson.annotation.JsonView;

import lombok.*;

@Getter
@Setter
@NodeEntity
@Schema(name="OntologyFileMetadata", description="POJO that represents the Ontology File Metadata")
public class OntologyFileMetadata extends Neo4jEntity {

    //@JsonView({View.Default.class, View.API.class})
    //@JsonProperty(value = "ontology")
    //protected String primaryKey;
    
	//private long id;
        @JsonView({View.API.class})
	private String defaultNamespace;
        @JsonView({View.API.class})
	private String owlAxioms;
        @JsonView({View.OntologyFileMetadata.class})
	private List<String> remark ;
        @JsonView({View.OntologyFileMetadata.class})
	private List<String> synonymtypedef = new ArrayList<String>();//
        @JsonView({View.OntologyFileMetadata.class})
        private List<String> property_value ;
        @JsonView({View.OntologyFileMetadata.class})
        private List<String> treatXrefsAsGenusDifferentia;
        @JsonView({View.API.class})
	private String autoGeneratedBy;
        @JsonView({View.API.class})
	private String savedBy;
        @JsonView({View.OntologyFileMetadata.class})
	private List<String> ontology = new ArrayList<String>();
        @JsonView({View.OntologyFileMetadata.class})
	private List<String> subsetdef = new ArrayList<String>();//
	@JsonView({View.API.class})
        @Convert(value = DateConverter.class)
	@JsonProperty(value = "releaseDate")
        private Date date;
        @JsonView({View.API.class}) 
       @JsonProperty(value = "releaseVersion")
        private String formatVersion;
    @JsonView({View.API.class})
    @Convert(value = DateConverter.class)
    private Date snapShotDate;

}
