name: PR validation
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]
    branches:
      - release-*
      - master

jobs:
  test-compile:
    if: github.event.action != 'edited' || github.event.changes.base
    runs-on: ubuntu-20.04
    steps:
      - name: Report workflow details
        run: |
          echo "Repository ${{ github.repository }}."
          echo "Trigger ref ${{ github.ref }}, base-ref ${{ github.base_ref }}, head_ref ${{ github.head_ref }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cp agr_api/src/main/resources/application.properties.defaults agr_api/src/main/resources/application.properties
      - name: Report files updated in PR
        run: |
          git fetch -q origin ${{ github.base_ref }} ${{ github.head_ref }}
          git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Report runtime details
        run: |
          echo "Github runner OS: ${{ runner.os }}"
      - name: Report Maven version
        run: |
          mvn --version
      - name: Package Everything
        run: |
          mvn -T 8 clean package -ntp -DskipTests=true

  test-build-docker-image:
    if: github.event.action != 'edited' || github.event.changes.base
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Amazon ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build docker image
        run: docker build -t agr_java_software:latest .
